version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: super-market
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://root:root@db:5432/super-market
    ports:
      - "8000:8000"
    volumes:
      - generated:/srv/generated

volumes:
  pgdata:
  generated:
