"""add daily_closures table

Revision ID: 349f23a28e9c
Revises: a61a19091113
Create Date: 2026-07-19 16:05:49.949710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349f23a28e9c'
down_revision: Union[str, Sequence[str], None] = 'a61a19091113'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_closures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('closure_date', sa.Date(), nullable=False),
    sa.Column('total_sales', sa.Float(), nullable=False),
    sa.Column('total_tax', sa.Float(), nullable=False),
    sa.Column('cash_total', sa.Float(), nullable=True),
    sa.Column('upi_total', sa.Float(), nullable=True),
    sa.Column('card_total', sa.Float(), nullable=True),
    sa.Column('other_total', sa.Float(), nullable=True),
    sa.Column('bill_count', sa.Integer(), nullable=True),
    sa.Column('top_items_json', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('closure_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_closures')
    # ### end Alembic commands ###
